### PR TITLE
Fix intermitent broken files when inlining

### LINKED ISSUE #56: intermitent broken files when inlining
sometimes files in dependencies come out broken (part of the file is missing therefore parens are not closed). gut feeling is that something goes wrong when files are processed in parallel.

example
```
fazekasbenedek@scatha:~/projects/cider-nrepl (master)$ make test
lein with-profile -user inline-deps
project prefix:  cider.nrepl.inlined-deps
retrieve dependencies and munge clojure source files
in RESOLVED-TREE mode, working on a resolved dependency tree
 [cljfmt "0.8.0" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
   [com.googlecode.java-diff-utils/diffutils "1.3.0"]
   [org.clojure/tools.cli "1.0.206"]
   [rewrite-clj "1.0.605-alpha"]
 [org.clojure/tools.namespace "1.0.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/java.classpath "1.0.0"]
 [compliment "0.3.11" :exclusions [[org.clojure/clojure]]]
 [org.clojure/tools.trace "0.7.10" :exclusions [[org.clojure/clojure]]]
 [org.rksm/suitable "0.4.0" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
 [cider/orchard "0.7.1" :exclusions [[org.clojure/clojure]]]
   [org.tcrawley/dynapath "1.1.0" :exclusions [[org.clojure/clojure]]]
 [org.clojure/tools.reader "1.3.2" :exclusions [[org.clojure/clojure]]]
 [fipp "0.6.24" :exclusions [[org.clojure/clojure]]]
   [org.clojure/core.rrb-vector "0.1.1"]
 [thunknyc/profile "0.5.2" :exclusions [[org.clojure/clojure]]]
 [mvxcvi/puget "1.3.1" :exclusions [[org.clojure/clojure]]]
   [mvxcvi/arrangement "1.2.0"]
unzipping [ orchard  [ v0v7v1 ]]
unzipping [ profile  [ v0v5v2 ]]
unzipping [ dynapath  [ v1v1v0 ]]
unzipping [ toolsnamespace  [ v1v0v0 ]]
unzipping [ cljfmt  [ v0v8v0 ]]
unzipping [ rewrite-clj  [ v1v0v605-alpha ]]
unzipping [ toolsreader  [ v1v3v2 ]]
unzipping [ suitable  [ v0v4v0 ]]
unzipping [ puget  [ v1v3v1 ]]
unzipping [ fipp  [ v0v6v24 ]]
unzipping [ corerrb-vector  [ v0v1v1 ]]
unzipping [ javaclasspath  [ v1v0v0 ]]
unzipping [ diffutils  [ v1v3v0 ]]
unzipping [ arrangement  [ v1v2v0 ]]
unzipping [ toolstrace  [ v0v7v10 ]]
unzipping [ toolscli  [ v1v0v206 ]]
unzipping [ compliment  [ v0v3v11 ]]
  munge source files of compliment artifact on branch [] exposed false.
  munge source files of toolscli artifact on branch [] exposed false.
  munge source files of toolstrace artifact on branch [] exposed false.
  munge source files of arrangement artifact on branch [] exposed false.
  munge source files of diffutils artifact on branch [] exposed false.
  munge source files of javaclasspath artifact on branch [] exposed false.
  munge source files of corerrb-vector artifact on branch [] exposed false.
  munge source files of fipp artifact on branch [] exposed false.
  munge source files of puget artifact on branch [] exposed false.
  munge source files of suitable artifact on branch [] exposed false.
  munge source files of toolsreader artifact on branch [] exposed false.
  munge source files of rewrite-clj artifact on branch [] exposed false.
  munge source files of cljfmt artifact on branch [] exposed false.
    prefixing imports in clojure files in 'target/srcdeps/cljfmt' ...
    prefixing imports: done
  munge source files of toolsnamespace artifact on branch [] exposed false.
  munge source files of dynapath artifact on branch [] exposed false.
  munge source files of profile artifact on branch [] exposed false.
  munge source files of orchard artifact on branch [] exposed false.
jaring all class file dependencies into target/class-deps.jar
prefixing #{"difflib"} in target/class-deps.jar with cidernrepl0270SNAPSHOT
deleting directories with class files in target/srcdeps...
   difflib  deleted
unzipping repackaged class-deps.jar into target/srcdeps
touch .inline-deps
lein with-profile -user,+1.10,+test,+plugin.mranderson/config test
Compiling 3 source files to /Users/fazekasbenedek/projects/cider-nrepl/target/classes
Syntax error reading source at (cider/nrepl/inlined_deps/toolsreader/v1v3v2/clojure/tools/reader/reader_types.clj:251:82).
Unmatched delimiter: ]
```

### PR DESCRIPTION
**Pull request by lread**
We had a wee bug which caused duplicate processing of the same source file for a single ns rename. Since we are, by default, processing files in parallel, this can lead to corrupt results.

This change:
- addresses the wee bug that caused duplicate processing: mranderson.util.remove-subdirs now also removes duplicate dirs.
- throws an internal error when duplicate files are detected prior to embarking on the ns rename processing

And also:
- any file-seq I noticed, I converted to non-lazy. These lazy file-seqs had me a bit confused during debugging, due to the way I was debugging, they were being resolved after files had changed on the filesystem.

Extra Testing

I did some extra testing using cider-nrepl v0.28.6 on macOS using Temurin 17.0.4.1 JDK. I ran 100 inline-dep generation runs against:
- current: 0.5.4-SNAPSHOT
- new: same but with this change

I compared target/srcdeps.

current:
- 13 of the 100 runs produced corrupt source files
- avg time to processs: 62.2s

new:
- 0 of 100 runs produced corrupt source files
- avg time to process: 53.8s

Closes #56

### CODE REVIEW

**Comment by benedekfazekas** [comment]
this is a very wlc PR 👏 . will have a proper look shortly

File: src/mranderson/move.clj [hunk 1]
```diff
@@ -292,12 +292,18 @@
...
-                      (->> (str file)
-                           util/file->extension
-                           (update-file file replace-ns-symbol old-sym new-sym watermark extension))))
-       (doall)))
+  (let [files (clojure-source-files dirs extension)
+        dupes (->> (map str files)
+                   frequencies
+                   (filterv #(> (second %) 1)))]
+    (if (seq dupes)
+      (throw (ex-info "internal error: found unexpected duplicates in files" {:dupes dupes}))
```
Comment (vemv) [inline src/mranderson/move.clj:300]: Looks like this path could get coverage?

File: src/mranderson/util.clj [hunk 2]
```diff
@@ -155,6 +155,7 @@
 
 (defn remove-subdirs [dirs]
   (->> (sort dirs)
+       distinct
```
Comment (vemv) [inline src/mranderson/util.clj:158]: In order for the `distinct` to be as useful as possible, `dirs` should be absolutized (or canonicalized? even better) beforehand

File: src/mranderson/move.clj [hunk 3]
```diff
@@ -292,12 +292,18 @@
...
-  (->> (clojure-source-files dirs extension)
-       (pmap-runner (fn [file]
-                      (->> (str file)
-                           util/file->extension
-                           (update-file file replace-ns-symbol old-sym new-sym watermark extension))))
-       (doall)))
+  (let [files (clojure-source-files dirs extension)
+        dupes (->> (map str files)
+                   frequencies
+                   (filterv #(> (second %) 1)))]
```
Comment (vemv) [inline src/mranderson/move.clj:298]:
```suggestion
        dupes (->> files
                   (map str)
                   (frequencies)
                   (filterv #(> (second %) 1)))]
```

Very subjective but this keeps the eyes consistently flowing in the same direction :)

Comment (vemv) [reply src/mranderson/move.clj:298]: Also `map str` could be subject to canonicalization? See other comment

**Review by vemv — COMMENTED** [review]
Some suggestions

File: src/mranderson/move.clj (hunk 1 above)
Comment (lread) [reply src/mranderson/move.clj:300]: Only if we have an unintentional programming error.

Comment (vemv) [reply src/mranderson/move.clj:300]: I mean, how do we know that the `frequencies` code works?

You could exercise that by intentionally invoking this defn with bad input.

File: src/mranderson/util.clj (hunk 2 above)
Comment (lread) [reply src/mranderson/util.clj:158]: That's a good point. I think the dirs do come in as fully qualified, but the current code leaves one wondering if that's the case.

File: src/mranderson/move.clj (hunk 3 above)
Comment (lread) [reply src/mranderson/move.clj:298]: On the subjective change... I don't have an objection but wouldn't bother with it.

Comment (lread) [reply src/mranderson/move.clj:298]: On the absolute file thing... yeah, probably a good idea.

**Comment by lread** [comment]
@vemv thanks for taking time to review, much appreciated!

File: src/mranderson/move.clj (hunk 3 above)
Comment (lread) [reply src/mranderson/move.clj:298]: On the subjective change... bah, I don't care! I'll commit your suggestion. 🙂

File: src/mranderson/move.clj (hunk 1 above)
Comment (lread) [reply src/mranderson/move.clj:301]: Oh right. A unit test. 🙂 Yeah can do.
This was the first change I put in and it get triggered before other fixes were put in.

**Comment by lread** [comment]
Ok @benedekfazekas, I've address @vemv's feedback, lemme know if you'd like any further changes.

**Comment by benedekfazekas** [comment]
thank you @lread much appreciated!

**Comment by lread** [comment]
My pleasure @benedekfazekas, glad to be of help!
